# Production context:
# All deploys from the main repository branch
# will inherit these settings.
[context.production]
  command = "yarn build"

# Branch deploy context:
# All deploys that are not from a pull/merge request
# or from the production branch will inherit these settings.
[context.branch-deploy]
  command = "yarn build:staging"


[[redirects]]
  from = "https://launch.hirightnow.com"
  to = "https://launch.hirightnow.co"
  status = 301
  force = true